### ISSUE TITLE
오탈자 : 먼저 알면 좋은 것들

### ISSUE THREAD

**Issue by minae27** [electronicnomad/plumbers-friday#31]
해당 부분에 "명령어" 부분에 오탈자가 있습니다 :) 참고를 부탁드립니다. 
![image](https://user-images.githubusercontent.com/25501159/116350149-631ffc00-a82c-11eb-9ff6-eceeb33f4664.png)

**Comment by electronicnomad** [comment]
감사합니다. 정정했습니다.
